---

base_locale: en
locales: [en]

ignore_unused:
  - "decidim.components.initiatives_no_signature_allowed.name"

ignore_missing:
  - decidim.participatory_processes.scopes.global
  - decidim.verifications.authorizations.first_login.actions.sms
